# Generated by Django 4.2.4 on 2023-11-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True, verbose_name='닉네임')),
                ('password', models.TextField(verbose_name='비밀번호')),
                ('people', models.IntegerField(verbose_name='사람 수')),
                ('store_id', models.CharField(max_length=40, verbose_name='가게이름')),
                ('soju_quantity', models.IntegerField(verbose_name='소주 병수')),
                ('beer_quantity', models.IntegerField(verbose_name='맥주 병수')),
                ('makguli_quantity', models.IntegerField(verbose_name='막거리 병수')),
                ('alcohol', models.IntegerField(verbose_name='알코올량')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
